### ISSUE TITLE
@override annotation in distance

### ISSUE THREAD

**Issue by amriteyapandey** [tdebatty/java-string-similarity#11]
`@override` annotation in `NGram.java` shows error in Java 6 and above. It should be removed as the method is not being overridden. It is just being implemented.

**Comment by mpkorstanje** [comment]
I'm afraid you are mistaken. If check the pom you you'll see this is a java 5 project. You may want to check your IDE's setting.

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.5</source>
                    <target>1.5</target>
                </configuration>
           </plugin>
```

**Comment by amriteyapandey** [comment]
I just saw that. Thanks

**Comment by tdebatty** [comment]
thank you @mpkorstanje !
