### ISSUE TITLE
Implement Damerau optimal string alignment

### ISSUE THREAD

**Issue by tdebatty** [tdebatty/java-string-similarity#16]

**Comment by MpoMp** [comment]
Here's a quick one, no tests yet, the Wikipedia example comparison works fine. 
[OSA source](https://github.com/MpoMp/java-string-similarity/blob/master/src/main/java/info/debatty/java/stringsimilarity/OptimalStringAlignment.java)

Let me know what you think. :)

**Comment by tdebatty** [comment]
Hi,
Looks nice!
Could you make a pull request?
And maybe write a small unit test based on the wikipedia example?
Thanks a lot!

**Comment by MpoMp** [comment]
Sure I'll do it asap because I am away from my desk!

**Comment by tdebatty** [comment]
Pull request merged, and new version released:
https://github.com/tdebatty/java-string-similarity/releases/tag/v0.18
Should be available on Maven within a few hours...
