### ISSUE TITLE
C# .NET Port

### ISSUE THREAD

**Issue by jamesmblair** [tdebatty/java-string-similarity#19]
I've created a port of your library to the .NET Framework using C#. The repository for the port is here: <https://github.com/feature23/StringSimilarity.NET>

Aside from changes to C# syntax, I made a few changes to make the code a bit more idiomatic for the language, but it's as true to the original as possible. Also I have, of course, linked back here to your original library. In any case, I just wanted to make you aware of the port, and please let me know if you have any interested in collaborating!

**Comment by tdebatty** [comment]
Hi,
Thanks for letting me know!
I mentioned your port in the Users section of the README...
Best regards,
