### ISSUE TITLE
Feature Request: Ability to store and specify profiles

### ISSUE THREAD

**Issue by hrj** [tdebatty/java-string-similarity#2]
### Use-case: Searching for a best match
Given a string `Q`, and a list of strings `L`, I want to find the distance between `Q` and every element of `L` and then pick the element with the shortest distance.

### Current solution
The current solution is to call a distance function with two String parameters. This function assumes nothing about the Strings and hence some information is recomputed every time (for example, profiles of a string).

### Proposal
Two additional APIs can be provided to improve performance:

```java
   Profile getProfile(String)

   double distance(Profile p1, Profile p2)
```

For convenience, a third API would also be useful:
```java
  double distance(Profile p, String s) {
    return distance(p, getProfile(s));
  }
```

This can be used like this:
```java
  String query = "alex";
  QGram qg = new QGram(2);
  Profile queryProfile = qg.getProfile(query);
  list forEach { element ->
    println(qg.distance(queryProfile, element));
  }
```

Further, if the list is going to be persistent, it could also be possible to serialize the profile of each element of the list into the persistent store. Then, both the query string and the list element's profile need not be recomputed every time!

--------
If the overall idea sounds good to you, I will write more about how the `Profile` type could be made type safe across the different implementations of `StringSimilarityInterface`.

**Comment by tdebatty** [comment]
Hello,

What you are describing here is the nearest neighbor search (nn-search)
problem, which is a very broad, and sometimes complicated topic.
It is actually the subject I'm currently investigating, and the reason why
I started implementing the string similarity library.
So I will definitely add some nn-search algorithms, but in a separate
project as there are a lot of algorithms and approaches that are possible.
I will try to create the project this week, and drop some starting code.
Then of course we could add some more fancy algorithms...

By the way, be aware that the algorithm you proposed will not necessarily
provide you with the most similar item, for example if the query string (Q)
contains a character sequence that was not present in the original dataset
(L). Nevertheless, I think the idea is still very interesting. I will also
try to investigate about it this week...

What do you think about this?

Regards,

Thibault

**Comment by hrj** [comment]
​Oh! I might have described this wrong.

I didn't mean to suggest an implementation of the search algorithm in this
project. Rather, some additional APIs in the similarity algorithms to help
speed up the search algorithms.

In my project, I have a crude implementation of the search algorithm that
could benefit from the above APIs. Would be great to see your research when
you publish it.

**Comment by tdebatty** [comment]
Hello,

Juste dropped a new release, with this modification in mind.
For Jaccard similarity, there is now a method
similarity(profile1, profile2)

Could you give this one a try?

If it works fine, I will probably add the same method to the other
shingle-based similaritiies (Cosine, Soresen and Q-Gram)

By the way, what is your project about? I'm quite curious about the kind
applications that use these algorithms...

Regards,

**Comment by hrj** [comment]
Hi! Thanks for considering my suggestions. But I am not sure whether the net result of your changes is going to improve performance. There are now HashMaps and Sets of strings instead of arrays of integers. I had imagined the changes would have been simpler, but maybe I was wrong.

My project involves management of patient records. They need to be searched by name and the search needs to be fuzzy since there are many spelling mistakes or alternative spellings in the records. I am using similarity measures to implement the fuzzy search.

**Comment by tdebatty** [comment]
Hello,

Just released a new version, that should be much more faster...

Let me know what you think about it...

Regards,

**Comment by hrj** [comment]
Whoa; you are moving very fast; hard for me to keep up :)

I am deep in another context for a couple of days. Will give you some feedback after I am back.

best,
hrj
