### ISSUE TITLE
Make KShingling threadsafe

### ISSUE THREAD

**Issue by tdebatty** [tdebatty/java-string-similarity#21]
https://github.com/tdebatty/java-string-similarity/blob/master/src/main/java/info/debatty/java/stringsimilarity/KShingling.java

In this way precomputing profiles could happen in parallel:
https://github.com/tdebatty/java-string-similarity/blob/master/src/main/java/info/debatty/java/stringsimilarity/examples/PrecomputedCosine.java

**Comment by mpkorstanje** [comment]
Seeing how the KShingling is actually a hash based multiset of a tokenized strings I think you should use that data structure instead. The [metric itself becomes ridiculously simple](https://github.com/Simmetrics/simmetrics/blob/149d6aca11a47d5e48102f3c3dd0cad2a4eadcfb/simmetrics-core/src/main/java/org/simmetrics/metrics/CosineSimilarity.java) when it operates on those data sets.

Creating the hash sets can then be done in parallel.

**Comment by tdebatty** [comment]
Thank you for the hint.
Is now fixed
