### ISSUE TITLE
sift4

### ISSUE THREAD

**Issue by kag0** [tdebatty/java-string-similarity#25]
I've made a java port of the sift4 common algorithm. https://siderite.blogspot.com/2014/11/super-fast-and-accurate-string-distance.html

Is there any interest in adding it here?

**Comment by tdebatty** [comment]
Hi,
Could be interesting, indeed!
Just, do you have some kind of theoretical document explaining the working of SIFT4, like a conference or journal paper? I think the page you mention lacks some theoretical explanation.
For example, what is the upper bound on the computed distance?
If I understand the algorithm correctly, the upper bound on computation cost is actually O(n . offset) if both strings are completely different? And the lower bound is O(n), when both strings are equal. And n is the length of the longest string?

**Comment by kag0** [comment]
I don't think @siderite has any more details than are on his post, it is largely a code reading exercise to understand its workings. 
If _I_ understand correctly, upper bound on distance should be something like the length of the longer string being compared. Your estimation of the costs seem correct to me as well.

**Comment by Siderite** [comment]
Yeah, sorry, guys! Not much on theory, me. I just wrote the thing and made it work for most cases. Then made it more generic.

**Comment by tdebatty** [comment]
Then maybe I could integrate it in a separate package "stringsimilarity.experimental" for algorithms that just work and are experimentally tested, although without theoretical background.

**Comment by kag0** [comment]
Sounds good to me. Only comment would be maybe either name the package something other than "experimental" or document somewhere that the code is production ready, it's just the algorithms that don't have a theoretical background.

**Comment by tdebatty** [comment]
Hi,
I added your java code and a basic test in a new branch sift4:
https://github.com/tdebatty/java-string-similarity/tree/sift4
https://github.com/tdebatty/java-string-similarity/commit/43354cac4b672d868bc05a087fcbe98c9e2ce567#diff-cc6f7c8f82621204f1c4d0661d24cbc0

According to https://siderite.blogspot.com/2014/11/super-fast-and-accurate-string-distance.html the result should be 11.

But the test currently fails (returns 10):
https://travis-ci.org/tdebatty/java-string-similarity/branches

Any idea?

**Comment by Siderite** [comment]
Haven't had the time to look at it in depth, but it might be the rounding. In .NET I had to add an extra MidpointRounding parameter to round away from zero and not the default which some economics crap that depends on whether the closest integer is odd or even. Maybe Java is similarly impaired,

**Comment by Siderite** [comment]
On second look there are no roundings involved. The longest string is 26 characters long, the lcss is 19, no matter the order in which they are taken and the transpositions are 4. So 26-(19-4)=11. The Java code seems to be an almost exact copy of the common algorithm without the maxDistance calculation. I don't see why your Java code would fail. Are you sure you are testing the code that appears at https://github.com/tdebatty/java-string-similarity/blob/sift4/src/main/java/info/debatty/java/stringsimilarity/experimental/Sift4.java with the test at https://github.com/tdebatty/java-string-similarity/blob/sift4/src/test/java/info/debatty/java/stringsimilarity/experimental/Sift4Test.java ? I don't see how it returns 10.

**Comment by Siderite** [comment]
I mean, I copied the code in Java, copy pasted it in an HTML file, turned it into Javascript, executed it, and it returned 11. :)

**Comment by kag0** [comment]
We can see [here](https://www.diffchecker.com/f2tRQaaJ) the differences are that in the java version there is no max distance (which isn't the problem, that can only cause the js version to return a smaller distance), and I've used a `LinkedList` in place of the js array. For the `LinkedList` it's safe to say that `push`, `size`/`length`, and `get(i)`/`[i]` all work the same as in js. The only other difference is `offset_arr.splice(i,1);` vs `offset_arr.remove(i);` In java this 
> Removes the element at the specified position in this list. Shifts any subsequent elements to the left (subtracts one from their indices).

So: unless that `splice` works differently than `remove` then we've got a funkier issue on our hands.
And for the record, running the java version locally does return 10 for me as well.

**Comment by tdebatty** [comment]
Pay attention that in Java, LinkedList.push() will add the element at the front of the list. It's the same behavior as stack.push().
If I'm correct (but I'm no JS specialist) the JavaScript code uses Array.push(), which adds the element at the end of the array. This might make a difference...

**Comment by Siderite** [comment]
It's a good catch, but inserting at the beginning of the array is arr.splice(0,0,item) in javascript and it makes no difference, the result is still 11. Can you debug and see what is going on? What are the various values at the end? I mean lcss and trans?

**Comment by kag0** [comment]
I'm (obviously) no js specialist either, but you're right. Good catch.
Changing push to add causes it to return 11 as desired.

updated https://gist.github.com/kag0/5fe7ba9f3f400c00c74698924e5fe4d0

for ref:
adding element to the end of the list:
```
lcss : 19
trans : 4
result: 11
```
adding element to front of the list
```
lcss : 19
trans : 3
result: 10
```

**Comment by Siderite** [comment]
Strange. I can't get it to return 10 in Javascript no matter if it pushes the value or inserts it. Anyway, good that it works now.

**Comment by Siderite** [comment]
Changed push to add in the Java implementation in the blog post.

**Comment by tdebatty** [comment]
Corrected and released...
