### ISSUE TITLE
Jaro-Winkler handling empty strings

### ISSUE THREAD

**Issue by dom9988** [tdebatty/java-string-similarity#28]
Hi,

When using jaro-winkler method I see that when comparing empty strings '' and '' the score return is 1, indicating a complete mismatch.

here is an example below implemented in scala

`val jaro = new JaroWinkler()`
`println(jaro.distance("",""))`
`println(jaro.distance("match","match"))`

Can this be altered so that when comparing empty strings it returns an exact match of 0?

Thanks

**Comment by tdebatty** [comment]
Hi,

As a quick fix, I would recommend you add the test to your own code...

From the theory point of view, I think for most algorithms the result of comparing two empty strings is actually undefined. Hence both implementations are correct. Comparing two empty strings can either return 0 or 1, it depends on the application.

For this library, I would like to be consistent, choose one option and implement it in all algorithms. And of course it would be best to know what the most common use case is...

**Comment by mpkorstanje** [comment]
From a developer perspective I would recommend that any similarity measure should be consistent with equals such that `a.equals(b)` => `compare(a,b) == 1.0`. For distance metrics `a.equals(b)` => `distance(a,b) == 0.0`.

This keeps everything consistent. e.g.

    "a".distance("b") == 1.0
    "a".distance("a") == 0.0
    "".distance("") == 0.0

**Comment by paulirwin** [comment]
Agreed with @mpkorstanje. Two empty strings are equal and should have a distance of 0. I'd be happy to submit a PR for this if no one else is working on it.

**Comment by dom9988** [comment]
@paulirwin that would be great and much appreciated
