### ISSUE TITLE
Re-authorize Coveralls

### ISSUE THREAD

**Issue by paulirwin** [tdebatty/java-string-similarity#30]
I was trying to look at the Coveralls data [here](https://coveralls.io/builds/9772547/source?filename=src%2Fmain%2Fjava%2Finfo%2Fdebatty%2Fjava%2Fstringsimilarity%2FShingleBased.java) and it can't show the source code because it says the repo owner must re-authorize with GitHub:

> SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

**Comment by tdebatty** [comment]
Strange...
I had to completely delete and reconfigure the coveralls repository. Apparently it's working now...
