### ISSUE TITLE
KShingling and StringProfile classes are not available

### ISSUE THREAD

**Issue by Aleyasen** [tdebatty/java-string-similarity#32]
These classes are not the latest release:
```
info.debatty.java.stringsimilarity.KShingling;
info.debatty.java.stringsimilarity.StringProfile;
```

**Comment by tdebatty** [comment]
Hi,

Indeed, at release 0.19 shingle based algorithms have been refactored, and these classes were dropped.

However, it is still possible to precompute string profiles, if this is what you need:
https://github.com/tdebatty/java-string-similarity/blob/master/src/main/java/info/debatty/java/stringsimilarity/examples/PrecomputedCosine.java

**Comment by Aleyasen** [comment]
@tdebatty Thanks for your quick reply. Could you please let me know what if I want to use Q-Gram with profile, what method I should use? `QGram` only has a `distance` method that the parameters are String not  Profile (or Map<String, Integer>).

**Comment by tdebatty** [comment]
@Aleyasen you're right, chame on me! :-/
I just added the required method and published a new release:
https://github.com/tdebatty/java-string-similarity/releases/tag/v0.23

It should be available on Maven central within a few hours...

**Comment by Aleyasen** [comment]
Wow, thank you very much for the quick release, I appreciate it :)
