### ISSUE TITLE
Damerau–Levenshtein and triangle equality

### ISSUE THREAD

**Issue by chrisjbroeren** [tdebatty/java-string-similarity#4]
Hi. I noticed something whilst browsing this git...

The readme states that the triangle inequality does not hold for the Demerau-Levenshtein algorithm. This is only true if you use a restricted edit distance implementation of the algorithm. If you allow for the 'unrestricted' case (of adjacent transpositions) the inequality will hold. This is, however, at the expense of added computational complexity. See [here](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Algorithm)

Implementing the adjacent transposition calc will allow you to use Demerau-Levenshtein in a metric tree, for example.

Cheers

Chris

**Comment by tdebatty** [comment]
Hi,

Thank you for the info!! I will update the readme!

Regards, and best wishes,

Thibault

**Comment by tdebatty** [comment]
Just corrected the README...
