### ISSUE TITLE
two questions about code architecture

### ISSUE THREAD

**Issue by akonsu** [tdebatty/java-string-similarity#40]
1. Would you explain why you decided not to make `StringDistance.distance()` static? Why is it necessary to create an instance of `StringDistance` (or of a derived class) to compute the distance? The method does not use `this` anyway...

2. Also, why `StringDistance` derives from `java.io.Serializable`?

**Comment by tdebatty** [comment]
Hi,

The main reason is that I started this library for my PhD. I use this code
to test Apache Spark algorithms with different similarity measures.
Therefore it was easier to have similarity objects (instead of static
methods), and Apache Spark required the Serializable interface...
