### ISSUE TITLE
Suggestion: "Typical Uses" column in Overview table

### ISSUE THREAD

**Issue by ADTC** [tdebatty/java-string-similarity#41]
Would it be possible for you to add a column called "Typical Uses" in the table in Overview? Perhaps to briefly mention where the algorithm is typically used (for example "diff utility, Git reconciliation" for LCS).

Not sure if you will have or can find this info. It will be helpful to pick out the algorithm best suited for the user's needs.

**Comment by tdebatty** [comment]
Hi,
Thank you for the suggestion. I just started a column, although for now I don't have a lot to fill..
Best regards,
