### ISSUE TITLE
Need to update README

### ISSUE THREAD

**Issue by artslob** [tdebatty/java-string-similarity#43]
In README paragraph:
https://github.com/tdebatty/java-string-similarity#shingle-n-gram-based-algorithms
There are import of classes that does not exist already:
import info.debatty.java.stringsimilarity.KShingling;
import info.debatty.java.stringsimilarity.StringProfile;

**Comment by tdebatty** [comment]
Hi! Thank you for your feedback! And sorry for the long delay!
The README is now updated!
Best regards!
