### ISSUE TITLE
Where is the SparseIntegerVector (and related) code?

### ISSUE THREAD

**Issue by SpamWall** [tdebatty/java-string-similarity#49]
Where is the SparseIntegerVector (and related) code?

**Comment by tdebatty** [comment]
They are not used anymore, and hence were removed. See commits 

* https://github.com/tdebatty/java-string-similarity/commit/5bec82bf5dced807d212e314bfc52decee232116
* https://github.com/tdebatty/java-string-similarity/commit/1afdc76eef523b144c73be3c3fc7df88f93fe9b7
