### ISSUE TITLE
Publish version 1.2.0 to maven central repo

### ISSUE THREAD

**Issue by AarjavP** [tdebatty/java-string-similarity#51]
Currently the latest version on maven central is [1.1.0](https://search.maven.org/artifact/info.debatty/java-string-similarity/1.1.0/jar)
The latest released version in 1.2.0 according to [releases](https://github.com/tdebatty/java-string-similarity/releases) page.

Thanks

**Comment by tdebatty** [comment]
Hi,
Apparently release 1.2.0 messed up and didn't reach maven central. For safety I created a new release 1.2.1:
https://github.com/tdebatty/java-string-similarity/releases/tag/v1.2.1
Should appear on maven central within a few hours...
https://search.maven.org/search?q=a:java-string-similarity
Best regards!
