### ISSUE TITLE
Cosine Similarity

### ISSUE THREAD

**Issue by manalalonaizan** [tdebatty/java-string-similarity#9]
Hello,

I just tried cosine similarity and the result was above 1!
My code is attached.

[ConsineSimilarity.zip](https://github.com/tdebatty/java-string-similarity/files/404964/ConsineSimilarity.zip)

**Comment by mpkorstanje** [comment]
Am able to reproduce this. Using Simmetrics with an n-gram size of 3 I'm getting a value of about .8 for the similarity. Feels about right, small n-gram, large files, should be very similar.

Simmetrics:
 - n-gram size: 3
 - Hello World vs Hello other World
   - a size: 9
   - b size: 16
   - dot product: 8
   - magnitudeA: 9
   - magnitudeB: 16
   - similarity: 2/3
 - file-1 vs file-2
   - a size: 2447923
   - b size: 4891
   - dot product: 2.2543616E7
   - magnitudeA: 1.00425882E10
   - magnitudeB: 76247.0
   - similarity: 0.81468433

Java String Similarity
 - n-gram size: 3
 - Hello World vs Hello other World
   - profile 1 size: 9
   - profile 2 size: 16
   - dot product: 8
   - magnitude profile 1: 9
   - magnitude profile 2: 16
   - similarity: 2/3
 - file-1 vs file-2
   - profile 1 size: 22795
   - profile 2 size: 22857
   - dot product: 2.186767E7
   - magnitude profile 1: 5.509833038E9
   - magnitude profile 2: 74055.0
   - similarity: 1.0825702768339371

Looks the magnitude of profile 1is half of what it should be. The magnitude of profile 2 is slightly smaller. Dot product seems to be about right. I don't see any obvious mistakes in the code but to shingling is a bit confusing to be honest.

**Comment by mpkorstanje** [comment]
Found it. Both norm and dotProduct multiply integers which overflow into negative values. These should be cast to doubles or floats before being multiplied.

```
    protected static double norm(int[] profile) {
        double agg = 0;

        for (int v : profile) {
            agg += v * v;
        }

        return Math.sqrt(agg);
    }

    protected static double dotProduct(int[] profile1, int[] profile2) {
        int length = Math.max(profile1.length, profile2.length);
        profile1 = java.util.Arrays.copyOf(profile1, length);
        profile2 = java.util.Arrays.copyOf(profile2, length);

        double agg = 0;
        for (int i = 0; i < length; i++) {
            agg += profile1[i] * profile2[i];
        }
        return agg;
    }
```

**Comment by tdebatty** [comment]
Hi,
Thanks @manalalonaizan for the feedback, and thanks (once again) @mpkorstanje for the debugging!
I juste made the correction.
I will make a new release later today.
But I will leave the issue open, as I should check the rest of the code for similar bugs!
